name: Weekly dependabot checks
on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 1 * *'

env:
  ORGANIZATION: returngis

jobs:
  evergreen:
    name: evergreen
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub application token
        id: generate-token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.GH_APPLICATION_ID }}
          application_private_key: ${{ secrets.GH_APPLICATION_PRIVATE_KEY }}
          organization: ${{ env.ORGANIZATION }}
          permissions: 'contents:write, pull_requests:write'
      - name: Run evergreen action
        uses: github/evergreen@v1.6.0
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          ORGANIZATION: ${{ env.ORGANIZATION }}
          #DRY_RUN: true
